[package]
name = "tafd-input"
version = "0.1.0"
edition = "2021"

[dependencies]
tafd-core = { path = "../tafd-core" }
log = "0.4"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.52", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_LibraryLoader",
    "Win32_System_Threading",
] }

[target.'cfg(target_os = "macos")'.dependencies]
core-graphics = "0.23"
core-foundation = "0.9"
libc = "0.2"

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"
